- name: Create scripts dir
  file: path="{{ scripts_dir }}" state=directory

- name: Copy files
  template: src={{ item }} dest="{{ scripts_dir }}/{{ item | basename | regex_replace('.j2','') }}" mode=u+x
  with_fileglob:
    - "{{ role_path }}/templates/*"
