- name: Generate dotfiles
  hosts: localhost
  connection: local
  vars:
    theme: molokai

  pre_tasks:
    - name: Create distdir
      file: path={{ dist_dir }} state=directory
    - name: Create config dir
      file: path={{ config_dir }} state=directory

  roles:
    - xresources
    - xdg
    - xsession
    - mpd
    - ncmpcpp
    - beets

- name: Generate scripts
  hosts: localhost
  connection: local
  roles:
    - scripts

- name: Create symlinks
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - stow

  post_tasks:
    - name: Symlink files into place
      shell: "./dotsetup -Sn"
      args:
        chdir: "{{ dist_dir }}"

# - name: Commit new generation
#   hosts: localhost
#   connection: local

#   tasks:
#     - name: Grab rev of main repo
#       shell: "git log --oneline | head -n 1 | cut -d' ' -f1"
#       register: main_repo_rev
#     - name: Remove timestamp
#       file: path="dist/.last-updated" state=absent
#     - name: Commit dist/ repo
#       shell: >
#         cd dist/ &&
#         echo "{{ ansible_date_time.iso8601 }}" > ".last-updated" &&
#         git add -A &&
#         git commit -m "Config files autogenerated at {{ ansible_date_time.iso8601 }} from {{ main_repo_rev.stdout }}"
